# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mpetruno <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/02/24 14:53:11 by mpetruno          #+#    #+#              #
#    Updated: 2018/02/24 20:01:09 by mpetruno         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-2

SRC = src/

INCL = inclu/

FLAGS = -Wall -Werror -Wextra

all:
	gcc $(SRC)*.c $(FLAGS) -I $(INCL) -o $(NAME)
fclean:
	rm -f $(NAME)
